# Generated by Django 2.2.28 on 2023-01-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221223_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dd',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
