# Generated by Django 2.2.28 on 2023-01-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
