# Generated by Django 2.2.28 on 2023-01-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_framework', to='apps.Framework'),
        ),
    ]
